# Generated by Django 4.2.2 on 2023-06-27 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContainerName', models.CharField(max_length=250)),
                ('MapLocationX', models.IntegerField()),
                ('MapLocationY', models.IntegerField()),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'containers',
            },
        ),
        migrations.CreateModel(
            name='ItemManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManufacturerName', models.CharField(max_length=250)),
                ('ManufacturerURL', models.URLField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=200)),
                ('StreetName', models.CharField(blank=True, max_length=250)),
                ('Number', models.CharField(blank=True, max_length=5)),
                ('PostalCode', models.CharField(blank=True, max_length=10)),
                ('Municipality', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=200)),
                ('Map', models.FileField(upload_to='')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=250)),
                ('ItemStatus', models.CharField(choices=[('NA', 'Not Applicable'), ('WK', 'Working'), ('DE', 'Defective'), ('RE', 'In Repair'), ('TE', 'In Test'), ('LO', 'Loaned out'), ('MS', 'Missing'), ('ST', 'Stolen')], default='NA', max_length=5)),
                ('ModelName', models.CharField(max_length=100)),
                ('ManufacturerURL', models.URLField(blank=True, max_length=250)),
                ('DatasheetURL', models.URLField(blank=True, max_length=250)),
                ('OwnerName', models.CharField(blank=True, max_length=250)),
                ('CurrentUser', models.CharField(blank=True, max_length=250)),
                ('Notes', models.TextField(blank=True, max_length=10000)),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('Container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.container')),
                ('ItemManufacturer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemmanufacturer')),
                ('ItemType', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemtype')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='ContainerRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room'),
        ),
    ]
