# Generated by Django 4.2.2 on 2023-06-27 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='itemmanufacturer',
            options={'verbose_name': 'item type', 'verbose_name_plural': 'item types'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'item type', 'verbose_name_plural': 'item types'},
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=200)),
                ('Map', models.FileField(blank=True, help_text='Optional top-down image of the area', upload_to='')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.AlterField(
            model_name='container',
            name='ContainerRoom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.area'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
