# Generated by Django 2.2.4 on 2019-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='floor_plan',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
