# Generated by Django 2.2.4 on 2019-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190820_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_sheet',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor_plan',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
