# Generated by Django 4.2.2 on 2023-06-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_area_alter_item_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
