# Generated by Django 2.2.4 on 2019-10-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20191001_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='data_sheet',
        ),
        migrations.CreateModel(
            name='ItemLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('url', models.URLField(blank=True, max_length=250)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ItemLinkType')),
            ],
        ),
    ]
