# Generated by Django 4.2.2 on 2023-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='order_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='Webshop/order URL'),
        ),
    ]
