# Generated by Django 2.2.4 on 2019-10-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20191022_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemLinks',
            new_name='ItemLink',
        ),
    ]
