# Generated by Django 4.2.2 on 2023-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_current_stock_item_in_stock_item_order_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
