# Generated by Django 2.2.4 on 2019-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20191022_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='itemlinktype',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
