# Generated by Django 2.2.8 on 2019-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20191102_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
