# Generated by Django 4.2.2 on 2023-06-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_category_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.container'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemmanufacturer'),
        ),
    ]
