# Generated by Django 4.2.2 on 2023-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_item_container_alter_item_item_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
